#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" != "test" ]; then
  echo "⚠️  Moviendo automáticamente el commit a la rama test..."

  # Guarda solo los archivos NO añadidos al staging
  git stash --keep-index  

  git checkout test  

  # Restaura solo los archivos que no estaban en staging
  git stash pop  

  # No usamos git add . porque ya estaban en staging
  exit 0
fi

echo "Ejecutando ESLint..."
npm run lint

echo "Ejecutando Prettier..."
npm run format

