#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
#!/bin/sh
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "test" ]; then
  echo "🚀 Pasando los cambios de test a main..."
  git checkout main
  git merge test
  git push origin main
  git checkout test
  exit 0
fi
